DECLARE @s date='2026-06-01', @e date='2026-06-30';

;WITH wages(role,wage) AS (SELECT * FROM (VALUES
    ('body contouring expert',25.454545454545453),
    ('clinic directorconcierge',20.77777777777778),
    ('clinical leadership team',0.0),
    ('esthetician',25.454545454545453),
    ('head md',125.0),
    ('manager',30.542857142857148),
    ('therapist',62.321851851851854),
    ('treatment provider',62.321851851851854),
    ('vp of clinical',120.1923076923077)
  ) v(role,wage)),
ffs_rates(service,latest_ffs,per_syringe) AS (SELECT * FROM (VALUES
    ('add-on 2nd area ipl photofacial',10.0,0),
    ('add-on 2nd area pca peel',7.5,0),
    ('add-on 2nd microneedling area',8.0,0),
    ('add-on 2nd morpheus8 area',10.0,0),
    ('add-on clear and brilliant 2nd area',6.0,0),
    ('add-on clear and brilliant 3rd area',10.0,0),
    ('add-on morpheus8 - prime tip',10.0,0),
    ('add-on morpheus8 - resurfacing tip',10.0,0),
    ('b12-injection',2.0,0),
    ('bbl - 10 syringes',225.0,0),
    ('bbl - 20 syringes',275.0,0),
    ('bbl - 30 syringes',325.0,0),
    ('bbl - 40 syringes',400.0,0),
    ('bbl - 50 syringes',525.0,0),
    ('belotero (balance)',25.0,1),
    ('botox',2.0,0),
    ('chemical peel',0.0,0),
    ('chemical peel (skinmedica)',0.0,0),
    ('clear and brilliant 1 treatment area (face, neck or chest)',12.0,0),
    ('complimentary consultation',0.0,0),
    ('coolsculpting elite',15.0,0),
    ('cryo skin 4.0 - body',0.0,0),
    ('cryoskin 4.0 facial',3.0,0),
    ('deep pore facial',9.0,0),
    ('dermal filler - sculptra',0.0,0),
    ('dermal fillers',0.0,0),
    ('dermaplane add-on',5.0,0),
    ('dermaplaning',6.75,0),
    ('diamondglow - brightening',0.0,0),
    ('diamondglow - even and correct',0.0,0),
    ('diamondglow - ha5',0.0,0),
    ('diamondglow - pore clairfying',0.0,0),
    ('diamondglow - tns',0.0,0),
    ('diamondglow body  lg (full back or full legs)',12.0,0),
    ('diamondglow body  md (full arms, buttocks or underarms)',8.0,0),
    ('diamondglow extraction add-on (large area)',3.0,0),
    ('diamondglow extraction add-on (small area)',3.0,0),
    ('diamondglow facial',6.75,0),
    ('dysport',8.0,0),
    ('emsculpt neo',5.25,0),
    ('evolysse form',12.5,1),
    ('evolysse smooth',12.5,1),
    ('express facial',6.75,0),
    ('extractions add-on (large area)',3.0,0),
    ('extractions add-on (small area)',3.0,0),
    ('facial - eye mask add-on',0.0,0),
    ('facial - led add-on',2.0,0),
    ('fire and ice facial',12.5,0),
    ('follow up',0.0,0),
    ('follow-up',0.0,0),
    ('good faith exam',5.0,0),
    ('hydrafacial',6.75,0),
    ('hydrafacial - deluxe facial',7.5,0),
    ('hydrafacial - eye perk treatment',2.25,0),
    ('hydrafacial - lip perk add-on',2.25,0),
    ('hydrafacial - lip perk treatment',2.25,0),
    ('hydrafacial - platinum facial',9.0,0),
    ('hydrojelly/cream mask -add-on',3.0,0),
    ('hylenex',5.0,0),
    ('instant bright eye mask add on',0.0,0),
    ('instant bright eye mask add-on',0.0,0),
    ('ipl add on 2nd area',10.0,0),
    ('ipl add-on 2nd area',10.0,0),
    ('ipl photofacial (1 area)',25.0,0),
    ('ipl spot treatment',10.0,0),
    ('jeuveau',2.0,0),
    ('juvederm (ultra plus)',5.0,1),
    ('juvederm (ultra)',5.0,1),
    ('juvederm (volbella)',5.0,1),
    ('juvederm (vollure)',5.0,1),
    ('juvederm (voluma)',5.0,1),
    ('juvederm half syringe (ultra)',5.0,1),
    ('juvederm upcharge 100',0.0,0),
    ('juvederm volbella (half syringe)',5.0,1),
    ('juvederm volux',5.0,1),
    ('kybella double chin treatment',15.0,1),
    ('laser genesis facial - face',17.5,0),
    ('laser genesis pigment/vascular',25.0,0),
    ('laser hair removal (buttocks)',15.0,0),
    ('laser hair removal (extra large)',0.0,0),
    ('laser hair removal (feet)',5.0,0),
    ('laser hair removal (full body)',24.0,0),
    ('laser hair removal (hands)',2.5,0),
    ('laser hair removal (jawline)',5.0,0),
    ('laser hair removal (large)',0.0,0),
    ('laser hair removal (lower body)',24.0,0),
    ('laser hair removal (medium)',0.0,0),
    ('laser hair removal (peri-a)',5.0,0),
    ('laser hair removal (side burns)',5.0,0),
    ('laser hair removal (small)',0.0,0),
    ('laser hair removal (stomach)',8.0,0),
    ('laser hair removal (upper body)',24.0,0),
    ('laser hair removal (upper lip)',5.0,0),
    ('laser hair removal areola',5.0,0),
    ('laser hair removal back',15.0,0),
    ('laser hair removal back and shoulders',20.0,0),
    ('laser hair removal bikini line',10.0,0),
    ('laser hair removal bikini line extended',15.0,0),
    ('laser hair removal brazilian',20.0,0),
    ('laser hair removal buttocks',15.0,0),
    ('laser hair removal cheeks',5.0,0),
    ('laser hair removal chest',15.0,0),
    ('laser hair removal chest and stomach',24.0,0),
    ('laser hair removal chin',5.0,0),
    ('laser hair removal face',10.0,0),
    ('laser hair removal face & neck',12.0,0),
    ('laser hair removal face and neck',12.0,0),
    ('laser hair removal feet',5.0,0),
    ('laser hair removal full arms',15.0,0),
    ('laser hair removal full bikini',15.0,0),
    ('laser hair removal full body',24.0,0),
    ('laser hair removal full body (clavicle down)',24.0,0),
    ('laser hair removal full body w/ face and neck',24.0,0),
    ('laser hair removal full face & neck',12.0,0),
    ('laser hair removal full legs',20.0,0),
    ('laser hair removal full lower face & neck',12.0,0),
    ('laser hair removal glabella (between eyebrows)',5.0,0),
    ('laser hair removal hands',2.5,0),
    ('laser hair removal jawline',5.0,0),
    ('laser hair removal linea trail',5.0,0),
    ('laser hair removal lip and chin',6.0,0),
    ('laser hair removal lower arms',10.0,0),
    ('laser hair removal lower body',24.0,0),
    ('laser hair removal lower face',10.0,0),
    ('laser hair removal lower legs',12.0,0),
    ('laser hair removal neck',8.0,0),
    ('laser hair removal outer ears',5.0,0),
    ('laser hair removal peri-a',5.0,0),
    ('laser hair removal shoulders',12.0,0),
    ('laser hair removal side burns',5.0,0),
    ('laser hair removal stomach',8.0,0),
    ('laser hair removal underarms',6.0,0),
    ('laser hair removal upper arms',10.0,0),
    ('laser hair removal upper body',24.0,0),
    ('laser hair removal upper legs',12.0,0),
    ('laser hair removal upper lip',5.0,0),
    ('laser pigment treatment',25.0,0),
    ('letybo',4.0,0),
    ('line tamer letybo upcharge',0.0,0),
    ('line tamer memberships merz 50',0.0,0),
    ('line tamer touch up',0.0,0),
    ('lip filler',0.0,0),
    ('lip flip/gummy smile',5.0,0),
    ('masseter tox - xeomin only',12.5,0),
    ('medical chart release consent',0.0,0),
    ('microneedling (1 area)',15.0,0),
    ('model consultation',0.0,0),
    ('morpheus8 rf microneedling (1 area)',20.0,0),
    ('morpheus8 rf microneedling - abdomen',20.0,0),
    ('nasal tox - xeomin only',5.0,0),
    ('nefertiti tox - xeomin only',7.5,0),
    ('new client consultation add-on',0.0,0),
    ('new quarterly toxin treatment',10.0,0),
    ('new quarterly xeomin treatment',10.0,0),
    ('non-surgical brazilian butt lift consultation',0.0,0),
    ('non-surgical brazilian butt lift mini (radiesse)',150.0,0),
    ('non-surgical brazilian butt lift ultimate (radiesse)',300.0,0),
    ('non-surgical butt lift consult',0.0,0),
    ('non-surgical mini bbl radiesse',150.0,0),
    ('non-surgical ultimate bbl radiesse',300.0,0),
    ('pca 4% retinol booster',5.0,0),
    ('pca 6% retinol booster',5.0,0),
    ('pca acne peel',0.0,0),
    ('pca advanced treatment booster',7.5,0),
    ('pca bright and even peel',0.0,0),
    ('pca chemical peel',12.5,0),
    ('pca peel',0.0,0),
    ('pca pigment correct peel',0.0,0),
    ('pca senci peel',0.0,0),
    ('pca ultra peel',0.0,0),
    ('pdrn tone-up add-on',7.5,0),
    ('pdrn tone-up add-on (2 areas)',10.0,0),
    ('platysmal band tox - xeomin only',10.0,0),
    ('prf add-on',12.0,0),
    ('prf gel',40.0,0),
    ('prf hair loss',25.0,0),
    ('prf rejuvenation injections (inc. undereye)',25.0,0),
    ('prf undereye + morpheus resurfacing',25.0,0),
    ('prf undereye + morpheus resurfacing or prime',25.0,0),
    ('prf/prp injectable upcharge',5.0,0),
    ('pro-nox',0.0,0),
    ('pronox add-on',0.0,0),
    ('provider consultation',0.0,0),
    ('provider follow up call',0.0,0),
    ('provider follow-up call',0.0,0),
    ('prp add-on',5.0,0),
    ('prp add-on 15ml',5.0,0),
    ('prp add-on 30ml',5.0,0),
    ('prp for hair loss',12.0,0),
    ('prp for hairloss',12.0,0),
    ('prp rejuvenation injections',12.0,0),
    ('prp rejuvenation injections (inc. undereye)',12.0,0),
    ('prp undereye & resurfacing rejuvenation',25.0,0),
    ('prp undereye + morpheus resurfacing tip',25.0,0),
    ('prp undereye resurfacing rejuvenation',25.0,0),
    ('quarterly toxin treatment',10.0,0),
    ('quarterly xeomin treatment',10.0,0),
    ('radiesse',20.0,1),
    ('radiesse (with lidocaine)',20.0,1),
    ('restylane (contour)',12.5,1),
    ('restylane - l',12.5,1),
    ('restylane defyne',12.5,1),
    ('restylane kysse',12.5,1),
    ('restylane lyft',15.0,1),
    ('restylane refyne',12.5,1),
    ('sculptra',15.0,1),
    ('signature facial',9.0,0),
    ('signature hydrafacial',6.75,0),
    ('signature laser facial - face',17.5,0),
    ('skincare consult',0.0,0),
    ('skinmedica peel - illuminize',12.0,0),
    ('skinmedica peel - rejuvnize',12.0,0),
    ('skinmedica peel - vitalize',12.0,0),
    ('skinvive',5.0,1),
    ('social media consent',0.0,0),
    ('subcision for scarring',5.0,0),
    ('topical letybo add-on',5.0,0),
    ('topical xeomin add-on',7.5,0),
    ('trap tox',25.0,0),
    ('underarm sweat reduction tox',25.0,0),
    ('undereye filler',0.0,0),
    ('versa',25.0,1),
    ('vi peel',15.0,0),
    ('vi peel - body',15.0,0),
    ('vi peel - precision plus',12.0,0),
    ('vi peel - precision+purify',12.0,0),
    ('vi peel - purify',12.0,0),
    ('wrinkle relaxer-2 areas (botox)',2.0,0),
    ('wrinkle relaxer-2 areas (dysport)',8.0,0),
    ('wrinkle relaxer-2 areas (jeuveau)',2.0,0),
    ('wrinkle relaxer-2 areas (letybo)',4.0,0),
    ('wrinkle relaxer-2 areas (xeomin)',10.0,0),
    ('wrinkle relaxer-3 areas (botox)',2.0,0),
    ('wrinkle relaxer-3 areas (dysport)',8.0,0),
    ('wrinkle relaxer-3 areas (jeuveau)',2.0,0),
    ('wrinkle relaxer-3 areas (letybo)',4.0,0),
    ('wrinkle relaxer-3 areas (xeomin)',10.0,0),
    ('wrinkle relaxer-new patient',0.0,0),
    ('wrinkle relaxers-existing patient',0.0,0),
    ('xeomin',10.0,0),
    ('xeomin - lower face bundle',0.0,0)
  ) v(service,latest_ffs,per_syringe)),
sched AS (
  SELECT center_name, LOWER(job_name) AS role, SUM((CASE WHEN scheduled_hours LIKE '%:%' THEN CAST(SUBSTRING(scheduled_hours,1,CHARINDEX(':',scheduled_hours)-1) AS FLOAT)+CAST(SUBSTRING(scheduled_hours,CHARINDEX(':',scheduled_hours)+1,LEN(scheduled_hours)) AS FLOAT)/60.0 ELSE COALESCE(TRY_CAST(scheduled_hours AS FLOAT),0) END)) AS hrs
  FROM dbo.V_ZENOTI_EMPLOYEE_SCHEDULES
  WHERE CAST([date] AS DATE) BETWEEN @s AND @e
  GROUP BY center_name, LOWER(job_name)),
base AS (SELECT sc.center_name, SUM(w.wage*sc.hrs) AS base
  FROM sched sc JOIN wages w ON w.role=sc.role GROUP BY sc.center_name),
cogs AS (
  SELECT center_name, LOWER(service_name) AS service, SUM(qty) AS qty, COUNT(DISTINCT invoice_no) AS occ
  FROM dbo.V_ZENOTI_COST_OF_GOODS
  WHERE CAST(transaction_date AS DATE) BETWEEN @s AND @e AND service_name IS NOT NULL
  GROUP BY center_name, LOWER(service_name)),
ffs AS (SELECT c.center_name, SUM(fr.latest_ffs*CASE WHEN fr.per_syringe=1 THEN c.qty ELSE c.occ END) AS ffs
  FROM cogs c JOIN ffs_rates fr ON fr.service=c.service GROUP BY c.center_name),
sales AS (
  SELECT center_name, SUM(sales_exc_tax) AS sales,
         SUM(CASE WHEN item_category IS NULL OR (item_category NOT LIKE 'Retail%' AND item_category<>'Memberships')
                  THEN sales_exc_tax ELSE 0 END) AS commissionable
  FROM dbo.V_ZENOTI_SALES_ACCRUAL
  WHERE CAST(sale_date AS DATE) BETWEEN @s AND @e
  GROUP BY center_name),
centers AS (SELECT center_name FROM base UNION SELECT center_name FROM ffs UNION SELECT center_name FROM sales),
calc AS (
  SELECT c.center_name, ISNULL(b.base,0) AS base, ISNULL(f.ffs,0) AS ffs,
         0.15*ISNULL(s.commissionable,0) AS comm, ISNULL(s.sales,0) AS sales_accrual
  FROM centers c
  LEFT JOIN base b ON b.center_name=c.center_name
  LEFT JOIN ffs  f ON f.center_name=c.center_name
  LEFT JOIN sales s ON s.center_name=c.center_name),
final AS (
  SELECT center_name, base, ffs, comm,
    (base+ffs+comm)*0.125 AS benefits,
    base+ffs+comm+(base+ffs+comm)*0.125 AS salary,
    sales_accrual
  FROM calc),
result AS (
  SELECT 0 AS sort_key, center_name,
    ROUND(base,2) AS base, ROUND(ffs,2) AS ffs, ROUND(comm,2) AS comm,
    ROUND(benefits,2) AS benefits, ROUND(salary,2) AS salary, ROUND(sales_accrual,2) AS sales_accrual,
    ROUND(salary/NULLIF(sales_accrual,0)*100,2) AS salary_margin_pct
  FROM final
  UNION ALL
  SELECT 1, 'ALL CENTERS (tile)',
    ROUND(SUM(base),2), ROUND(SUM(ffs),2), ROUND(SUM(comm),2),
    ROUND(SUM(benefits),2), ROUND(SUM(salary),2), ROUND(SUM(sales_accrual),2),
    ROUND(SUM(salary)/NULLIF(SUM(sales_accrual),0)*100,2)
  FROM final)
SELECT center_name, base, ffs, comm, benefits, salary, sales_accrual, salary_margin_pct
FROM result
ORDER BY sort_key, center_name;
