/* ============================================================================
   Payroll / Salary-Margin verification  (generated from payroll_schedules.json)
   Run on sql-prod-cus-evolve. Replicates utils/payroll.py exactly.
   Rates (wages, FFS, factors) are inlined below so this matches the deployed app.
   Read-only. Regenerate if the supporting-schedules Excel changes.
   ============================================================================ */
DECLARE @e DATE = (SELECT MAX(CAST(payment_date AS DATE)) FROM dbo.BRONZE_ZENOTI_CASH_COLLECTIONS);
DECLARE @s DATE = DATEFROMPARTS(YEAR(@e), MONTH(@e), 1);
DECLARE @benefits FLOAT = 0.125;
DECLARE @comm     FLOAT = 0.15;

;WITH wages(role, rate) AS (VALUES
    ('body contouring expert', 25.454545454545453),
    ('clinic directorconcierge', 20.77777777777778),
    ('clinical leadership team', 0.0),
    ('esthetician', 25.454545454545453),
    ('head md', 125.0),
    ('manager', 30.542857142857148),
    ('therapist', 62.321851851851854),
    ('treatment provider', 62.321851851851854),
    ('vp of clinical', 120.1923076923077)
),
ffs(item, per_syringe, latest_ffs) AS (VALUES
    ('add-on 2nd area ipl photofacial', 0, 10.0),
    ('add-on 2nd area pca peel', 0, 7.5),
    ('add-on 2nd microneedling area', 0, 8.0),
    ('add-on 2nd morpheus8 area', 0, 10.0),
    ('add-on clear and brilliant 2nd area', 0, 6.0),
    ('add-on clear and brilliant 3rd area', 0, 10.0),
    ('add-on morpheus8 - prime tip', 0, 10.0),
    ('add-on morpheus8 - resurfacing tip', 0, 10.0),
    ('b12-injection', 0, 2.0),
    ('bbl - 10 syringes', 0, 225.0),
    ('bbl - 20 syringes', 0, 275.0),
    ('bbl - 30 syringes', 0, 325.0),
    ('bbl - 40 syringes', 0, 400.0),
    ('bbl - 50 syringes', 0, 525.0),
    ('belotero (balance)', 1, 25.0),
    ('botox', 0, 2.0),
    ('chemical peel', 0, 0.0),
    ('chemical peel (skinmedica)', 0, 0.0),
    ('clear and brilliant 1 treatment area (face, neck or chest)', 0, 12.0),
    ('complimentary consultation', 0, 0.0),
    ('coolsculpting elite', 0, 15.0),
    ('cryo skin 4.0 - body', 0, 0.0),
    ('cryoskin 4.0 facial', 0, 3.0),
    ('deep pore facial', 0, 9.0),
    ('dermal filler - sculptra', 0, 0.0),
    ('dermal fillers', 0, 0.0),
    ('dermaplane add-on', 0, 5.0),
    ('dermaplaning', 0, 6.75),
    ('diamondglow - brightening', 0, 0.0),
    ('diamondglow - even and correct', 0, 0.0),
    ('diamondglow - ha5', 0, 0.0),
    ('diamondglow - pore clairfying', 0, 0.0),
    ('diamondglow - tns', 0, 0.0),
    ('diamondglow body  lg (full back or full legs)', 0, 12.0),
    ('diamondglow body  md (full arms, buttocks or underarms)', 0, 8.0),
    ('diamondglow extraction add-on (large area)', 0, 3.0),
    ('diamondglow extraction add-on (small area)', 0, 3.0),
    ('diamondglow facial', 0, 6.75),
    ('dysport', 0, 8.0),
    ('emsculpt neo', 0, 5.25),
    ('evolysse form', 1, 12.5),
    ('evolysse smooth', 1, 12.5),
    ('express facial', 0, 6.75),
    ('extractions add-on (large area)', 0, 3.0),
    ('extractions add-on (small area)', 0, 3.0),
    ('facial - eye mask add-on', 0, 0.0),
    ('facial - led add-on', 0, 2.0),
    ('fire and ice facial', 0, 12.5),
    ('follow up', 0, 0.0),
    ('follow-up', 0, 0.0),
    ('good faith exam', 0, 5.0),
    ('hydrafacial', 0, 6.75),
    ('hydrafacial - deluxe facial', 0, 7.5),
    ('hydrafacial - eye perk treatment', 0, 2.25),
    ('hydrafacial - lip perk add-on', 0, 2.25),
    ('hydrafacial - lip perk treatment', 0, 2.25),
    ('hydrafacial - platinum facial', 0, 9.0),
    ('hydrojelly/cream mask -add-on', 0, 3.0),
    ('hylenex', 0, 5.0),
    ('instant bright eye mask add on', 0, 0.0),
    ('instant bright eye mask add-on', 0, 0.0),
    ('ipl add on 2nd area', 0, 10.0),
    ('ipl add-on 2nd area', 0, 10.0),
    ('ipl photofacial (1 area)', 0, 25.0),
    ('ipl spot treatment', 0, 10.0),
    ('jeuveau', 0, 2.0),
    ('juvederm (ultra plus)', 1, 5.0),
    ('juvederm (ultra)', 1, 5.0),
    ('juvederm (volbella)', 1, 5.0),
    ('juvederm (vollure)', 1, 5.0),
    ('juvederm (voluma)', 1, 5.0),
    ('juvederm half syringe (ultra)', 1, 5.0),
    ('juvederm upcharge 100', 0, 0.0),
    ('juvederm volbella (half syringe)', 1, 5.0),
    ('juvederm volux', 1, 5.0),
    ('kybella double chin treatment', 1, 15.0),
    ('laser genesis facial - face', 0, 17.5),
    ('laser genesis pigment/vascular', 0, 25.0),
    ('laser hair removal (buttocks)', 0, 15.0),
    ('laser hair removal (extra large)', 0, 0.0),
    ('laser hair removal (feet)', 0, 5.0),
    ('laser hair removal (full body)', 0, 24.0),
    ('laser hair removal (hands)', 0, 2.5),
    ('laser hair removal (jawline)', 0, 5.0),
    ('laser hair removal (large)', 0, 0.0),
    ('laser hair removal (lower body)', 0, 24.0),
    ('laser hair removal (medium)', 0, 0.0),
    ('laser hair removal (peri-a)', 0, 5.0),
    ('laser hair removal (side burns)', 0, 5.0),
    ('laser hair removal (small)', 0, 0.0),
    ('laser hair removal (stomach)', 0, 8.0),
    ('laser hair removal (upper body)', 0, 24.0),
    ('laser hair removal (upper lip)', 0, 5.0),
    ('laser hair removal areola', 0, 5.0),
    ('laser hair removal back', 0, 15.0),
    ('laser hair removal back and shoulders', 0, 20.0),
    ('laser hair removal bikini line', 0, 10.0),
    ('laser hair removal bikini line extended', 0, 15.0),
    ('laser hair removal brazilian', 0, 20.0),
    ('laser hair removal buttocks', 0, 15.0),
    ('laser hair removal cheeks', 0, 5.0),
    ('laser hair removal chest', 0, 15.0),
    ('laser hair removal chest and stomach', 0, 24.0),
    ('laser hair removal chin', 0, 5.0),
    ('laser hair removal face', 0, 10.0),
    ('laser hair removal face & neck', 0, 12.0),
    ('laser hair removal face and neck', 0, 12.0),
    ('laser hair removal feet', 0, 5.0),
    ('laser hair removal full arms', 0, 15.0),
    ('laser hair removal full bikini', 0, 15.0),
    ('laser hair removal full body', 0, 24.0),
    ('laser hair removal full body (clavicle down)', 0, 24.0),
    ('laser hair removal full body w/ face and neck', 0, 24.0),
    ('laser hair removal full face & neck', 0, 12.0),
    ('laser hair removal full legs', 0, 20.0),
    ('laser hair removal full lower face & neck', 0, 12.0),
    ('laser hair removal glabella (between eyebrows)', 0, 5.0),
    ('laser hair removal hands', 0, 2.5),
    ('laser hair removal jawline', 0, 5.0),
    ('laser hair removal linea trail', 0, 5.0),
    ('laser hair removal lip and chin', 0, 6.0),
    ('laser hair removal lower arms', 0, 10.0),
    ('laser hair removal lower body', 0, 24.0),
    ('laser hair removal lower face', 0, 10.0),
    ('laser hair removal lower legs', 0, 12.0),
    ('laser hair removal neck', 0, 8.0),
    ('laser hair removal outer ears', 0, 5.0),
    ('laser hair removal peri-a', 0, 5.0),
    ('laser hair removal shoulders', 0, 12.0),
    ('laser hair removal side burns', 0, 5.0),
    ('laser hair removal stomach', 0, 8.0),
    ('laser hair removal underarms', 0, 6.0),
    ('laser hair removal upper arms', 0, 10.0),
    ('laser hair removal upper body', 0, 24.0),
    ('laser hair removal upper legs', 0, 12.0),
    ('laser hair removal upper lip', 0, 5.0),
    ('laser pigment treatment', 0, 25.0),
    ('letybo', 0, 4.0),
    ('line tamer letybo upcharge', 0, 0.0),
    ('line tamer memberships merz 50', 0, 0.0),
    ('line tamer touch up', 0, 0.0),
    ('lip filler', 0, 0.0),
    ('lip flip/gummy smile', 0, 5.0),
    ('masseter tox - xeomin only', 0, 12.5),
    ('medical chart release consent', 0, 0.0),
    ('microneedling (1 area)', 0, 15.0),
    ('model consultation', 0, 0.0),
    ('morpheus8 rf microneedling (1 area)', 0, 20.0),
    ('morpheus8 rf microneedling - abdomen', 0, 20.0),
    ('nasal tox - xeomin only', 0, 5.0),
    ('nefertiti tox - xeomin only', 0, 7.5),
    ('new client consultation add-on', 0, 0.0),
    ('new quarterly toxin treatment', 0, 10.0),
    ('new quarterly xeomin treatment', 0, 10.0),
    ('non-surgical brazilian butt lift consultation', 0, 0.0),
    ('non-surgical brazilian butt lift mini (radiesse)', 0, 150.0),
    ('non-surgical brazilian butt lift ultimate (radiesse)', 0, 300.0),
    ('non-surgical butt lift consult', 0, 0.0),
    ('non-surgical mini bbl radiesse', 0, 150.0),
    ('non-surgical ultimate bbl radiesse', 0, 300.0),
    ('pca 4% retinol booster', 0, 5.0),
    ('pca 6% retinol booster', 0, 5.0),
    ('pca acne peel', 0, 0.0),
    ('pca advanced treatment booster', 0, 7.5),
    ('pca bright and even peel', 0, 0.0),
    ('pca chemical peel', 0, 12.5),
    ('pca peel', 0, 0.0),
    ('pca pigment correct peel', 0, 0.0),
    ('pca senci peel', 0, 0.0),
    ('pca ultra peel', 0, 0.0),
    ('pdrn tone-up add-on', 0, 7.5),
    ('pdrn tone-up add-on (2 areas)', 0, 10.0),
    ('platysmal band tox - xeomin only', 0, 10.0),
    ('prf add-on', 0, 12.0),
    ('prf gel', 0, 40.0),
    ('prf hair loss', 0, 25.0),
    ('prf rejuvenation injections (inc. undereye)', 0, 25.0),
    ('prf undereye + morpheus resurfacing', 0, 25.0),
    ('prf undereye + morpheus resurfacing or prime', 0, 25.0),
    ('prf/prp injectable upcharge', 0, 5.0),
    ('pro-nox', 0, 0.0),
    ('pronox add-on', 0, 0.0),
    ('provider consultation', 0, 0.0),
    ('provider follow up call', 0, 0.0),
    ('provider follow-up call', 0, 0.0),
    ('prp add-on', 0, 5.0),
    ('prp add-on 15ml', 0, 5.0),
    ('prp add-on 30ml', 0, 5.0),
    ('prp for hair loss', 0, 12.0),
    ('prp for hairloss', 0, 12.0),
    ('prp rejuvenation injections', 0, 12.0),
    ('prp rejuvenation injections (inc. undereye)', 0, 12.0),
    ('prp undereye & resurfacing rejuvenation', 0, 25.0),
    ('prp undereye + morpheus resurfacing tip', 0, 25.0),
    ('prp undereye resurfacing rejuvenation', 0, 25.0),
    ('quarterly toxin treatment', 0, 10.0),
    ('quarterly xeomin treatment', 0, 10.0),
    ('radiesse', 1, 20.0),
    ('radiesse (with lidocaine)', 1, 20.0),
    ('restylane (contour)', 1, 12.5),
    ('restylane - l', 1, 12.5),
    ('restylane defyne', 1, 12.5),
    ('restylane kysse', 1, 12.5),
    ('restylane lyft', 1, 15.0),
    ('restylane refyne', 1, 12.5),
    ('sculptra', 1, 15.0),
    ('signature facial', 0, 9.0),
    ('signature hydrafacial', 0, 6.75),
    ('signature laser facial - face', 0, 17.5),
    ('skincare consult', 0, 0.0),
    ('skinmedica peel - illuminize', 0, 12.0),
    ('skinmedica peel - rejuvnize', 0, 12.0),
    ('skinmedica peel - vitalize', 0, 12.0),
    ('skinvive', 1, 5.0),
    ('social media consent', 0, 0.0),
    ('subcision for scarring', 0, 5.0),
    ('topical letybo add-on', 0, 5.0),
    ('topical xeomin add-on', 0, 7.5),
    ('trap tox', 0, 25.0),
    ('underarm sweat reduction tox', 0, 25.0),
    ('undereye filler', 0, 0.0),
    ('versa', 1, 25.0),
    ('vi peel', 0, 15.0),
    ('vi peel - body', 0, 15.0),
    ('vi peel - precision plus', 0, 12.0),
    ('vi peel - precision+purify', 0, 12.0),
    ('vi peel - purify', 0, 12.0),
    ('wrinkle relaxer-2 areas (botox)', 0, 2.0),
    ('wrinkle relaxer-2 areas (dysport)', 0, 8.0),
    ('wrinkle relaxer-2 areas (jeuveau)', 0, 2.0),
    ('wrinkle relaxer-2 areas (letybo)', 0, 4.0),
    ('wrinkle relaxer-2 areas (xeomin)', 0, 10.0),
    ('wrinkle relaxer-3 areas (botox)', 0, 2.0),
    ('wrinkle relaxer-3 areas (dysport)', 0, 8.0),
    ('wrinkle relaxer-3 areas (jeuveau)', 0, 2.0),
    ('wrinkle relaxer-3 areas (letybo)', 0, 4.0),
    ('wrinkle relaxer-3 areas (xeomin)', 0, 10.0),
    ('wrinkle relaxer-new patient', 0, 0.0),
    ('wrinkle relaxers-existing patient', 0, 0.0),
    ('xeomin', 0, 10.0),
    ('xeomin - lower face bundle', 0, 0.0)
),
base AS (   -- base salary = role wage x scheduled hours, per center
    SELECT s.center_name,
           SUM((CASE WHEN s.scheduled_hours LIKE '%:%' THEN CAST(SUBSTRING(s.scheduled_hours,1,CHARINDEX(':',s.scheduled_hours)-1) AS FLOAT) + CAST(SUBSTRING(s.scheduled_hours,CHARINDEX(':',s.scheduled_hours)+1,LEN(s.scheduled_hours)) AS FLOAT)/60.0 ELSE COALESCE(TRY_CAST(s.scheduled_hours AS FLOAT),0) END) * w.rate) AS base_salary
    FROM dbo.BRONZE_ZENOTI_EMPLOYEE_SCHEDULES s
    JOIN wages w ON LOWER(s.job_name) = w.role
    WHERE CAST(s.date AS DATE) BETWEEN @s AND @e
    GROUP BY s.center_name
),
cogs_agg AS (
    SELECT center_name, LOWER(service_name) AS service, SUM(qty) AS qty,
           COUNT(DISTINCT invoice_no) AS occ
    FROM dbo.BRONZE_ZENOTI_COST_OF_GOODS
    WHERE CAST(transaction_date AS DATE) BETWEEN @s AND @e AND service_name IS NOT NULL
    GROUP BY center_name, LOWER(service_name)
),
ffs_cte AS (   -- FFS: per-syringe -> qty; else Latest FFS once per service occurrence
    SELECT g.center_name,
           SUM(f.latest_ffs * (CASE WHEN f.per_syringe = 1 THEN g.qty ELSE g.occ END)) AS ffs
    FROM cogs_agg g JOIN ffs f ON f.item = g.service
    GROUP BY g.center_name
),
sales AS (
    SELECT center_name, SUM(sales_exc_tax) AS sales_accrual
    FROM dbo.BRONZE_ZENOTI_SALES_ACCRUAL
    WHERE CAST(sale_date AS DATE) BETWEEN @s AND @e
    GROUP BY center_name
)
SELECT
    sa.center_name                                              AS location,
    CAST(COALESCE(b.base_salary,0) AS DECIMAL(18,2))            AS base,
    CAST(COALESCE(fc.ffs,0)        AS DECIMAL(18,2))            AS ffs,
    CAST(@comm * sa.sales_accrual  AS DECIMAL(18,2))            AS comm,
    CAST((COALESCE(b.base_salary,0)+COALESCE(fc.ffs,0)+@comm*sa.sales_accrual)*@benefits AS DECIMAL(18,2)) AS benefits,
    CAST((COALESCE(b.base_salary,0)+COALESCE(fc.ffs,0)+@comm*sa.sales_accrual)*(1+@benefits) AS DECIMAL(18,2)) AS salary,
    CAST(sa.sales_accrual          AS DECIMAL(18,2))            AS sales_accrual,
    CAST((COALESCE(b.base_salary,0)+COALESCE(fc.ffs,0)+@comm*sa.sales_accrual)*(1+@benefits)
         / NULLIF(sa.sales_accrual,0) * 100 AS DECIMAL(8,2))   AS salary_margin_pct
FROM sales sa
LEFT JOIN base    b  ON b.center_name  = sa.center_name
LEFT JOIN ffs_cte fc ON fc.center_name = sa.center_name
ORDER BY sa.center_name;
