"""
Build data/overlay/overlay_setup.sql from the Zenoti CSV exports in data/overlay/.

Purpose: fill the gap when the bronze warehouse tables lag the live site (e.g. the
latest day's rows not yet ingested). The generated SQL:

  1. Clones each bronze table's schema into an OVERLAY_* staging table
     (SELECT TOP 0 * INTO ... — no need to know the full column list).
  2. Loads the CSV rows into the OVERLAY table (mapping report column names ->
     bronze column names; unmapped bronze columns stay NULL).
  3. Creates a V_* view = bronze UNION ALL overlay-for-dates-the-bronze-lacks
     (gap-fill: WHERE overlay.<date> > MAX(bronze.<date>) — so once the pipeline
     catches up, the overlay contributes nothing = no double-count).

The app then points FULL_* at the V_* views when OVERLAY_ENABLED=true (config.py).
Views are drop-in table replacements, so NO query changes are needed.

Re-run after dropping newer CSV exports in data/overlay/. To remove entirely:
drop the V_* views and OVERLAY_* tables (or set OVERLAY_ENABLED=false).
"""
import csv
import os

DATA = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "data", "overlay")
OUT = os.path.join(DATA, "overlay_setup.sql")

# Per table: csv file, bronze table, date column, and {bronze_col: csv_header} map.
# Only columns the app actually queries are loaded; the rest of the cloned schema
# stays NULL. Where the CSV lacks a column the app uses, we best-effort map or omit.
TABLES = [
    {
        "csv": "sales-accrual.csv", "bronze": "dbo.BRONZE_ZENOTI_SALES_ACCRUAL", "date": "sale_date",
        "map": {
            "sale_date": "Sale Date", "sales_exc_tax": "Sales (Exc. Tax)", "sales_inc_tax": "Sales(Inc. Tax)",
            "status": "Invoice status", "item_category": "Item Category", "item_sub_category": "Item Subcategory",
            "item_type": "Item Type", "item_name": "Item Name", "center_name": "Center Name",
            "guest_name": "Guest Name", "invoice_no": "Invoice No", "serviced_by": "Sold By", "sold_by": "Sold By",
        },
    },
    {
        "csv": "sales-cash.csv", "bronze": "dbo.BRONZE_ZENOTI_CASH_COLLECTIONS", "date": "payment_date",
        "map": {
            "payment_date": "Payment Date", "sales_collected_exc_tax": "Sales Collected (Exc.Tax)",
            "payment_type": "Payment Type", "member": "Member", "first_visit": "First Visit",
            "guest_name": "Guest Name", "guest_code": "Guest Code", "item_category": "Item Category",
            "center_name": "Center Name",
        },
    },
    {
        "csv": "cost-of-goods.csv", "bronze": "dbo.BRONZE_ZENOTI_COST_OF_GOODS", "date": "transaction_date",
        "map": {
            "transaction_date": "Transaction Date", "cost_of_goods": "Cost Of Goods", "service_name": "Service Name",
            "product_name": "Product Name", "qty": "Qty", "center_name": "Center Name", "invoice_no": "Invoice No",
        },
    },
    {
        "csv": "appointments.csv", "bronze": "dbo.BRONZE_ZENOTI_APPOINTMENTS", "date": "appointment_date",
        "map": {
            "appointment_date": "Appointment Date", "status": "Status", "add_on": "Add-on", "rebooked": "Rebooked",
            "invoice_no": "Invoice No", "guest_code": "Guest Code", "guest_name": "Guest Name",
            "first_visit": "First Visit", "service_name": "Service Name", "service_category": "Service Category",
            "providers": "Providers", "center_name": "Center Name", "checkin_time": "Checkin Time",
            "start_time": "Start Time", "actual_duration": "Actual Duration",
        },
    },
    {
        "csv": "attendance.csv", "bronze": "dbo.BRONZE_ZENOTI_EMPLOYEE_SCHEDULES", "date": "date",
        "map": {
            "date": "Date", "employee_name": "Employee Name", "job_name": "Job", "status": "Schedule Status",
            "center_name": "Work Center", "block_out_hours_paid": "Block Out Hours Paid",
            "scheduled_hours": "Scheduled Hours", "booked_hours": "Booked Hours",
        },
    },
]


def overlay_name(bronze: str) -> str:
    return bronze.replace("dbo.BRONZE_", "dbo.OVERLAY_")


def view_name(bronze: str) -> str:
    return bronze.replace("dbo.BRONZE_", "dbo.V_")


def read_rows(path):
    rows = list(csv.reader(open(path, encoding="utf-8-sig")))
    hi = next((i for i, r in enumerate(rows) if sum(1 for c in r if c.strip()) > 3), 0)
    hdr = rows[hi]
    idx = {h: j for j, h in enumerate(hdr)}
    data = [r for r in rows[hi + 1:] if any(c.strip() for c in r)]
    return idx, data


# Bronze columns that are integer-typed — the CSV gives them as '1.0000', which
# won't implicitly convert to int, so coerce to a whole number.
_INT_COLS = {"qty"}


def sql_val(v, col=None):
    v = (v or "").strip()
    if v == "":
        return "NULL"
    if col in _INT_COLS:
        try:
            return str(int(round(float(v))))
        except ValueError:
            return "NULL"
    return "'" + v.replace("'", "''") + "'"


def main():
    out = ["-- AUTO-GENERATED by scripts/build_overlay_sql.py — Zenoti overlay setup.",
           "-- Run once to create OVERLAY_* staging tables + V_* views (gap-fill, self-disabling).",
           "-- Remove: DROP the V_* views and OVERLAY_* tables (or set OVERLAY_ENABLED=false).",
           ""]
    for t in TABLES:
        bronze = t["bronze"]; ov = overlay_name(bronze); vw = view_name(bronze); dcol = t["date"]
        idx, data = read_rows(os.path.join(DATA, t["csv"]))
        cols = [c for c in t["map"] if t["map"][c] in idx]     # bronze cols we can populate
        collist = ", ".join(cols)
        ov_unq = ov.split(".")[-1]
        out.append(f"-- ===== {bronze} ({len(data)} overlay rows) =====")
        # Fresh clone every run (drop leftovers from failed runs). The DROP of the
        # base overlay table is safe even if V_* references it (non-schemabound view).
        out.append(f"IF OBJECT_ID('{ov}','U') IS NOT NULL DROP TABLE {ov};")
        out.append(f"SELECT TOP 0 * INTO {ov} FROM {bronze};")
        out.append("GO")
        # The clone copies NOT NULL constraints but not defaults/identity, so any
        # NOT-NULL column we don't populate (e.g. row_id, ingestion_timestamp) would
        # reject the INSERT. Make every non-identity NOT-NULL column NULLable.
        # (Own batch + GO so the INSERT below compiles against the new schema.)
        out.append(
            "DECLARE @s nvarchar(max)=N'';\n"
            f"SELECT @s=@s+'ALTER TABLE {ov} ALTER COLUMN ['+c.COLUMN_NAME+'] '+c.DATA_TYPE+"
            "CASE WHEN c.DATA_TYPE IN ('varchar','nvarchar','char','nchar','binary','varbinary') "
            "THEN '('+CASE WHEN c.CHARACTER_MAXIMUM_LENGTH=-1 THEN 'max' ELSE CAST(c.CHARACTER_MAXIMUM_LENGTH AS varchar(11)) END+')' "
            "WHEN c.DATA_TYPE IN ('decimal','numeric') THEN '('+CAST(c.NUMERIC_PRECISION AS varchar(11))+','+CAST(c.NUMERIC_SCALE AS varchar(11))+')' "
            "WHEN c.DATA_TYPE IN ('datetime2','time','datetimeoffset') THEN '('+CAST(ISNULL(c.DATETIME_PRECISION,7) AS varchar(11))+')' "
            "ELSE '' END+' NULL;' "
            f"FROM INFORMATION_SCHEMA.COLUMNS c WHERE c.TABLE_SCHEMA='dbo' AND c.TABLE_NAME='{ov_unq}' "
            f"AND c.IS_NULLABLE='NO' AND COLUMNPROPERTY(OBJECT_ID('{ov}'),c.COLUMN_NAME,'IsIdentity')=0;\n"
            "EXEC sys.sp_executesql @s;")
        out.append("GO")
        # batched INSERTs (<=500 rows per statement)
        B = 500
        for i in range(0, len(data), B):
            chunk = data[i:i + B]
            out.append(f"INSERT INTO {ov} ({collist}) VALUES")
            vals = []
            for r in chunk:
                vals.append("(" + ", ".join(sql_val(r[idx[t['map'][c]]], c) for c in cols) + ")")
            out.append(",\n".join(vals) + ";")
        out.append("GO")
        # gap-fill view: overlay only contributes dates the bronze doesn't have yet
        out.append(
            f"CREATE OR ALTER VIEW {vw} AS "
            f"SELECT * FROM {bronze} "
            f"UNION ALL "
            f"SELECT * FROM {ov} ov "
            f"WHERE CAST(ov.{dcol} AS DATE) > (SELECT MAX(CAST({dcol} AS DATE)) FROM {bronze});\nGO")
        out.append("")
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(out))
    print("SAVED", OUT)


if __name__ == "__main__":
    main()
